### PR TITLE
Fix `root` when not started using `npm start`

### PR DESCRIPTION
**Pull request by theotterlord**
Just a quick fix for the `root` getter that allows it to work when not using `npm start`.

### CODE REVIEW

**Comment by JortvD** [comment]
Ah, that looks way better indeed. I'll quickly test it and merge.

**Comment by JortvD** [comment]
Welp, I see the entry file (index.js) is currently inside the source directory. The root folder should be one folder higher or we can move the index.js file into the root directory.

**Comment by theotterlord** [comment]
Ah, nice catch. I think the first option is best, as it helps to keep the overall structure.

**Comment by JortvD** [comment]
Well, it's working, so I'll merge. Thank you!

**Pull request merged**
