### PR TITLE
Add validation to user creation

### PR DESCRIPTION
**Pull request by theotterlord**
I've added some validation for the user creation endpoint. 
It doesn't check if the username has been used yet, but does make sure that all data is of the correct type. 

Just filling in a TODO, but if there is anything specific you want me to do, let me know 😄

### CODE REVIEW

**Comment by JortvD** [comment]
Hmm. While I really like this method of validation, I think we should maybe move the validation of a property of the data object into it's own function. This function can, if the validation determines the input is incorrect, send an error to end the request and then return true, which informs the api to then stop from going on with handling the request. As the ApiRequest class already caches the body when it is loaded maybe it should also contain the validate function?

**Comment by JortvD** [comment]
As for something to do, I think I'd be smart we start with some better logging functionality. To files, different log levels, timestamps, timers, etc.

**Comment by theotterlord** [comment]
I've made the change. I think this is probably the best way of implementing it. As we are testing if it is a valid key, returning true when it is valid I think makes the most sense.

Yeah, I'll get started on a logging system in another branch. I also need to build a program to test ijo locally. I'll probably just knock something up in python to send requests to the API

**Comment by JortvD** [comment]
Yeah, I use Postman to test the api, but we should probably also get some code up to truly test it.

**Comment by JortvD** [comment]
But to get on topic, I also like this way more. One small thing: I think it might be neat to cache the parsed json body in the ApiRequest and then use that in the validation method instead of needing to supply the data objects. What are your thoughts on this?

**Comment by theotterlord** [comment]
> Yeah, I use Postman to test the api, but we should probably also get some code up to truly test it.

Yeah, probably best to create a seperate issue/branch for adding testing

>  I think it might be neat to cache the parsed json body in the ApiRequest and then use that in the validation method instead of needing to supply the data objects

Yeah, this does make more sense. I'll see what it looks like now

**Comment by theotterlord** [comment]
I've made the change, ~but I'm not sure if it is just worth just calling it at construction time. I suppose it depends if the body is needed every time or if sometimes it is loaded for no reason (in specific end points)~

**Comment by JortvD** [comment]
Ah, this is indeed what I was thinking of. The only thing I found while testing this was that the status code should have been 400 instead of 500, as the error is expected for the given input. I'll change it and merge this pr. Thanks for the help!

**Comment by theotterlord** [comment]
Ah, yeah. Forgot about 400 errors 😆

No prob. Gonna work on logging next 😄

**Comment by JortvD** [comment]
I'm also moving the api code to the utils, as I need it for the registry and might also use it for on the daemons.

**Comment by theotterlord** [comment]
Ah, ok. I guess it makes sense

**Comment by theotterlord** [comment]
Quick question then. Would it make sense to add logging to utils instead of the main repo?

**Comment by JortvD** [comment]
Oh, I hadn't thought of that. That might be very useful indeed. You can pr directly into the ijo-sm/ijo-utils repo if you want to add code there.

**Comment by theotterlord** [comment]
Cool, shall do that now

**Pull request merged**
